# Generated by Django 3.0.3 on 2020-04-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipmapping',
            old_name='ipaddress',
            new_name='rev_ipaddress',
        ),
        migrations.AddField(
            model_name='ipmapping',
            name='sro_ipaddress',
            field=models.GenericIPAddressField(default='127.0.0.1'),
            preserve_default=False,
        ),
    ]
